### ISSUE TITLE
Building package r-desolve for win64 failed when using recipe properly

### ISSUE THREAD

**Issue by ajoros** [conda/conda-recipes#334]
Hi all,

First timer at creating custom conda packages here. Not sure if this is the correct domain for this question, but I am attempting to create a conda package for desolve (differential equation library for R) on win64 but am running into multiple errors. My colleague has already created a linux64 version of this at https://binstar.org/vitale232/r-desolve. Since I assumed this was a compiling issue on Windows , I attempted to install mingw and mingw-w64 as compilers but am still receiving the errors below. Have been looking online extensively without an success. Any insight or tips would be appreciated

Here is what my win64 command window is exiting:
```
C:/Anaconda/envs/_build/R/etc/x64/Makeconf:202: warning: overriding commands for target `.m.o'
C:/Anaconda/envs/_build/R/etc/x64/Makeconf:195: warning: ignoring old commands for target `.m.o'
gcc -m64 -I"C:/Anaconda/envs/_build/R/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=core2 -c DLLutil.c -o DLLutil.o
'gcc' is not recognized as an internal or external command,
operable program or batch file.
C:\Anaconda\Scripts\make.exe: *** [DLLutil.o] Error 1
Warning: running command 'make -f "Makevars" -f "C:/Anaconda/envs/_build/R/etc/x64/Makeconf" -f "C:/Anaconda/envs/_build/R/share/make/winshlib.mk" SHLIB="deSolve.dll" SHLIB_LIBADD='$(FLIBS)' WIN=64 TCLBIN=64 OBJECTS="DLLutil.o R_init_deSolve.o brent.
o call_daspk.o call_euler.o call_iteration.o call_lsoda.o call_radau.o call_rk4.o call_rkAuto.o call_rkFixed.o call_rkImplicit.o call_zvode.o daux.o ddaspk.o deSolve_utils.o dintdy2.o dlinpk.o dlsoder.o dsparsk.o dvode.o errmsg.o ex_Aquaphy.o ex_CCL4
model.o ex_ChemicalDAE.o ex_SCOC.o forcings.o lags.o opkda1.o opkdmain.o radau5.o radau5a.o rk_auto.o rk_fixed.o rk_implicit.o rk_util.o rprintf.o twoDmap.o zvode.o"' had status 2
ERROR: compilation failed for package 'deSolve'
* removing 'C:/Anaconda/envs/_build/R/library/deSolve'
```

Below is the meta.yaml
```
package:
  name: r-desolve
  version: "1.11"

source:
  fn: deSolve_1.11.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/deSolve_1.11.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/deSolve/deSolve_1.10-9.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r

  run:
    - r

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('deSolve')" # [not win]
    - "\"%R%\" -e \"library('deSolve')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.
```

Below is the bld.bat used:
```
"%R%" CMD INSTALL --build .
if errorlevel 1 exit 1

@rem Add more build steps here, if they are necessary.

@rem See
@rem http://docs.continuum.io/conda/build.html
@rem for a list of environment variables that are set during the build process.
```
